/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/companies logos/anydo.gltf --output ./AnyDo.tsx -r ./public --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
    mesh_1: THREE.Mesh
    mesh_2: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function AnyDo(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/companies logos/anydo.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-2.5, 2.5, 0]} rotation={[Math.PI, 0, 0]} scale={[0.012, 0.012, 0.5]}>
        <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
        <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} position={[0, 0, -0.25]} />
        <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} position={[0, 0, -0.5]} />
      </group>
    </group>
  )
}

useGLTF.preload('/companies logos/anydo.gltf')
