/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { Html, useGLTF } from "@react-three/drei";
import { JSX } from "react";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube008: THREE.Mesh;
    Cube008_1: THREE.Mesh;
    Cube008_2: THREE.Mesh;
    keyboard: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    touchbar: THREE.Mesh;
  };
  materials: {
    aluminium: THREE.MeshStandardMaterial;
    ["matte.001"]: THREE.MeshStandardMaterial;
    ["screen.001"]: THREE.MeshStandardMaterial;
    keys: THREE.MeshStandardMaterial;
    trackpad: THREE.MeshStandardMaterial;
    touchbar: THREE.MeshStandardMaterial;
  };
};

export function MacbookPro16Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/macbook.glb") as GLTFResult;
  const isClosed = false;
  const rotateX = isClosed ? Math.PI / 2 : 0;
  return (
    <group {...props} dispose={null}>
      <group rotation-x={rotateX}>
        <group position={[0, 2.96, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            material={materials.aluminium}
            geometry={nodes.Cube008.geometry}
          />
          <mesh
            material={materials["matte.001"]}
            geometry={nodes.Cube008_1.geometry}
          />
          <mesh geometry={nodes.Cube008_2.geometry} material-color="black">
            {/* Drei's HTML component can "hide behind" canvas geometry */}
            <Html
              distanceFactor={3.3}
              transform
              rotation-x={-Math.PI / 2}
              wrapperClass="laptop"
              position={[0, 0.05, -0.09]}
              occlude="blending"
            >
              {/* eslint-disable-next-line @eslint-react/dom/no-missing-iframe-sandbox */}
              <iframe
                src="https://nirtamir.com"
                className="h-[670px] w-[1024px] rounded-xl border-none"
                title="Nir Tamir's Website"
              />
            </Html>
          </mesh>
        </group>
      </group>
      <mesh
        material={materials.keys}
        position={[1.79, 0, 3.45]}
        geometry={nodes.keyboard.geometry}
      />
      <group position={[0, -0.1, 3.39]}>
        <mesh
          material={materials.aluminium}
          geometry={nodes.Cube002.geometry}
        />
        <mesh
          material={materials.trackpad}
          geometry={nodes.Cube002_1.geometry}
        />
      </group>
      <mesh
        material={materials.touchbar}
        position={[0, -0.03, 1.2]}
        geometry={nodes.touchbar.geometry}
      />
    </group>
  );
}

useGLTF.preload("/macbook.glb");
